/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Viewss;

import DomainModels.ChiTietSP;
import DomainModels.HoaDon;
import DomainModels.HoaDonChiTiet;
import DomainModels.KhachHang;
import Repositories.HoaDonRepository;
import Services.ChiTietSPService;
import Services.HDCTService;
import Services.HoaDonBanHangService;
import Services.HoaDonServiceImpl;
import Services.Interface.ChiTietSPServiceInterface;
import Services.Interface.HoaDonBanHangServiceInterface;
import Services.Interface.HoaDonService;
import Services.KhachHangService;
import ViewModels.ChiTietSPViewModel;
import ViewModels.HoaDonBanHangViewModel;
import ViewModels.HoaDonChiTietViewModel;
import ViewModels.HoaDonViewModel;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Random;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dinhq
 */
public class BanHang extends javax.swing.JPanel {

    private ChiTietSPServiceInterface chiTietSPService;
    private HoaDonBanHangServiceInterface hoaDonBanHangService;
    private HDCTService HDCT;
    private KhachHangService serviceKH = new KhachHangService();
    private DefaultTableModel dtmKH = new DefaultTableModel();
    DefaultTableModel dtmSpBH = new DefaultTableModel();
    private List<KhachHang> listKH = new ArrayList<>();
    private List<ChiTietSPViewModel> listCTSPVM = new ArrayList<>();
    private HoaDonService hoadonService = new HoaDonServiceImpl();

    private DefaultTableModel defaultTableModelGioHang;
    private DefaultTableModel tableHoaDon;
    private HoaDonRepository hoaDonRepository = new HoaDonRepository();
    private ArrayList<HoaDonViewModel> lsthd = new ArrayList<>();

    ArrayList<HoaDonChiTietViewModel> listhdct = new ArrayList<>();
    ArrayList<HoaDonChiTiet> listhdctt = new ArrayList<>();

    /**
     * Creates new form BanHang
     */
    public BanHang() {
        initComponents();
        this.chiTietSPService = new ChiTietSPService();
        this.hoaDonBanHangService = new HoaDonBanHangService();
        this.HDCT = new HDCTService();
        loadTableHoaDonBanHang();
        loadTableChiTietSPBH();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void loadTableHoaDonBanHang() {
        DefaultTableModel modeltb = new DefaultTableModel();
        List<HoaDonBanHangViewModel> list = hoaDonBanHangService.all();
        modeltb = (DefaultTableModel) tbHoaDonBanHang.getModel();
        modeltb.setRowCount(0);
        for (HoaDonBanHangViewModel hoaDon : list) {
            modeltb.addRow(new Object[]{
                hoaDon.getMaHD(),
                hoaDon.getNgayTao(),
                hoaDon.getTinhTrang() == 0 ? "Chờ xử lý" : "Ðã thanh toán"});
        }
    }
    
     private void loadTableChiTietSPBH() {
        List<ChiTietSPViewModel> Sz = chiTietSPService.all();
        dtmSpBH = (DefaultTableModel) tbldssanpham.getModel();
        dtmSpBH.setRowCount(0);
        for (ChiTietSPViewModel x : Sz) {
            dtmSpBH.addRow(new Object[]{
                x.getSanPham().getMaSP(), x.getSanPham().getTenSP(), x.getDonGia(),
                x.getSoLuong(), x.getTrangThai() == 1 ? "Còn Hàng" : "Hết Hàng"});
        }
    }
     
     private void addTableGioHang(ArrayList<HoaDonChiTietViewModel> list) {
        defaultTableModelGioHang = (DefaultTableModel) tblgiohang.getModel();
        defaultTableModelGioHang.setRowCount(0);
        for (HoaDonChiTietViewModel chiTietHoaDonViewModel : list) {
            defaultTableModelGioHang.addRow(new Object[]{
                chiTietHoaDonViewModel.getMaSP(), chiTietHoaDonViewModel.getTenSP(), chiTietHoaDonViewModel.getSoLuong(), chiTietHoaDonViewModel.getDonGia(),
                chiTietHoaDonViewModel.getSoLuong() * chiTietHoaDonViewModel.getDonGia().doubleValue()
            });
        }
    }
     
    

    private void searchSPBH(List<ChiTietSPViewModel> list) {
        dtmSpBH.setRowCount(0);
        for (ChiTietSPViewModel chiTietSPViewModel : list) {
            dtmSpBH.addRow(chiTietSPViewModel.toDataRow());
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBanHang = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblgiohang = new javax.swing.JTable();
        btnxoa = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        btnnext = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbldssanpham = new javax.swing.JTable();
        txttimkiem = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        btnthem = new javax.swing.JButton();
        btntimkiem = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane22 = new javax.swing.JScrollPane();
        tbHoaDonBanHang = new javax.swing.JTable();
        jPanel54 = new javax.swing.JPanel();
        txttenkh1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        btnxacnhan1 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaHdBH = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        rdTienMat = new javax.swing.JRadioButton();
        rdChuyenKhoan = new javax.swing.JRadioButton();
        btnthanhtoan2 = new javax.swing.JButton();
        txtGhiChu1 = new javax.swing.JTextField();
        txtTienDu1 = new javax.swing.JLabel();
        txtKhachTra1 = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        LBtime = new javax.swing.JLabel();
        btnhuyhd = new javax.swing.JButton();
        btntaohd1 = new javax.swing.JButton();
        cbMaNhanVien = new javax.swing.JComboBox<>();
        txtThanhTien1 = new javax.swing.JTextField();
        cbTenKH = new javax.swing.JComboBox<>();
        txtSDTKhachHang = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();

        pnlBanHang.setBackground(new java.awt.Color(255, 255, 255));
        pnlBanHang.setPreferredSize(new java.awt.Dimension(1070, 760));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setPreferredSize(new java.awt.Dimension(1070, 760));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Giỏ Hàng"));

        tblgiohang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblgiohang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblgiohangMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblgiohang);

        btnxoa.setBackground(new java.awt.Color(204, 204, 204));
        btnxoa.setText("Sửa số lượng");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(456, 456, 456)
                .addComponent(btnxoa)
                .addGap(0, 154, Short.MAX_VALUE))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnxoa)
                .addGap(11, 11, 11))
        );

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Sản Phẩm"));

        tbldssanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên Sản phẩm", "Đơn giá", "Số Lượng", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbldssanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldssanphamMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbldssanpham);

        jLabel36.setText("1/3");

        btnthem.setBackground(new java.awt.Color(204, 204, 204));
        btnthem.setText("Thêm vào giỏ Hàng");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btntimkiem.setBackground(new java.awt.Color(204, 204, 204));
        btntimkiem.setText("Tìm kiếm");
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setText("Tên SP");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnnext, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(btnthem)
                .addGap(17, 17, 17))
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btntimkiem))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5)))
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntimkiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnback)
                    .addComponent(jLabel36)
                    .addComponent(btnnext)
                    .addComponent(btnthem))
                .addContainerGap())
        );

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Hoá Đơn"));

        tbHoaDonBanHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã", "Ngày Tạo", "Tình Trạng"
            }
        ));
        tbHoaDonBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHoaDonBanHangMouseClicked(evt);
            }
        });
        jScrollPane22.setViewportView(tbHoaDonBanHang);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 42, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel54.setBackground(new java.awt.Color(255, 255, 255));
        jPanel54.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "thông tin chung", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        txttenkh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttenkh1ActionPerformed(evt);
            }
        });

        jLabel28.setText("Tên KH");

        jLabel31.setText("Ngày Tạo");

        btnxacnhan1.setBackground(new java.awt.Color(204, 204, 204));
        btnxacnhan1.setText("Lấy thông tin");
        btnxacnhan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxacnhan1ActionPerformed(evt);
            }
        });

        jLabel32.setText("Mã nhân viên");

        jLabel6.setText("Mã hóa đơn");

        jLabel51.setText("Hình thức TT");

        rdTienMat.setText("Tiền mặt");

        rdChuyenKhoan.setText("Chuyển khoản");

        btnthanhtoan2.setBackground(new java.awt.Color(204, 204, 204));
        btnthanhtoan2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnthanhtoan2.setText("Thanh Toán");
        btnthanhtoan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthanhtoan2ActionPerformed(evt);
            }
        });

        txtTienDu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTienDu1.setForeground(new java.awt.Color(0, 0, 153));
        txtTienDu1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtTienDu1.setText("VND");

        txtKhachTra1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtKhachTra1CaretUpdate(evt);
            }
        });

        jLabel59.setText("Thành tiền");

        jLabel60.setText("Tiền khách trả");

        jLabel61.setText("Tiền dư");

        jLabel62.setText("Ghi chú");

        LBtime.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        LBtime.setForeground(new java.awt.Color(255, 51, 51));
        LBtime.setText("         ");
        LBtime.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                LBtimeAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btnhuyhd.setBackground(new java.awt.Color(204, 204, 204));
        btnhuyhd.setText("Hủy hóa đơn");
        btnhuyhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhuyhdActionPerformed(evt);
            }
        });

        btntaohd1.setBackground(new java.awt.Color(204, 204, 204));
        btntaohd1.setText("Tạo hóa đơn");
        btntaohd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntaohd1ActionPerformed(evt);
            }
        });

        txtThanhTien1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtThanhTien1CaretUpdate(evt);
            }
        });

        cbTenKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtSDTKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTKhachHangActionPerformed(evt);
            }
        });

        jLabel29.setText("SĐT");

        javax.swing.GroupLayout jPanel54Layout = new javax.swing.GroupLayout(jPanel54);
        jPanel54.setLayout(jPanel54Layout);
        jPanel54Layout.setHorizontalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel54Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btntaohd1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnhuyhd)
                .addGap(72, 72, 72))
            .addGroup(jPanel54Layout.createSequentialGroup()
                .addGroup(jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel54Layout.createSequentialGroup()
                        .addGroup(jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaHdBH)
                            .addComponent(cbMaNhanVien, 0, 151, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel54Layout.createSequentialGroup()
                        .addGroup(jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel54Layout.createSequentialGroup()
                                .addGap(0, 9, Short.MAX_VALUE)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel54Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel51)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel54Layout.createSequentialGroup()
                                .addComponent(cbTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttenkh1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnxacnhan1))
                            .addGroup(jPanel54Layout.createSequentialGroup()
                                .addComponent(rdTienMat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdChuyenKhoan)))
                        .addGap(4, 4, 4)))
                .addContainerGap())
            .addGroup(jPanel54Layout.createSequentialGroup()
                .addGroup(jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel54Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel54Layout.createSequentialGroup()
                                .addGroup(jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel59)
                                    .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel60, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel61, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGhiChu1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTienDu1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtThanhTien1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtKhachTra1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))))
                            .addGroup(jPanel54Layout.createSequentialGroup()
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LBtime, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel54Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnthanhtoan2)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel54Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSDTKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel54Layout.setVerticalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel54Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMaHdBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel54Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel54Layout.createSequentialGroup()
                        .addComponent(cbMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(LBtime))
                .addGap(14, 14, 14)
                .addGroup(jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttenkh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(btnxacnhan1)
                    .addComponent(cbTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSDTKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(18, 18, 18)
                .addGroup(jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdTienMat)
                    .addComponent(rdChuyenKhoan)
                    .addComponent(jLabel51))
                .addGap(25, 25, 25)
                .addGroup(jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel59)
                    .addComponent(txtThanhTien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel60)
                    .addComponent(txtKhachTra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTienDu1))
                .addGroup(jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel54Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel62))
                    .addGroup(jPanel54Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtGhiChu1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnthanhtoan2)
                .addGap(18, 18, 18)
                .addGroup(jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntaohd1)
                    .addComponent(btnhuyhd))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBanHangLayout = new javax.swing.GroupLayout(pnlBanHang);
        pnlBanHang.setLayout(pnlBanHangLayout);
        pnlBanHangLayout.setHorizontalGroup(
            pnlBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanHangLayout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        pnlBanHangLayout.setVerticalGroup(
            pnlBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBanHangLayout.createSequentialGroup()
                .addGroup(pnlBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlBanHangLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1301, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 1301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblgiohangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblgiohangMouseClicked
        // TODO add your handling code here:
        //        int ro = tblgiohang.getSelectedRow();
        //        txtThanhTien1.setText(tblgiohang.getValueAt(ro, 4).toString());
    }//GEN-LAST:event_tblgiohangMouseClicked

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        String sl = JOptionPane.showInputDialog("Mời nhập số lượng");
        int slm = Integer.valueOf(sl);
        HoaDonChiTiet hd = new HoaDonChiTiet();
        int row = tblgiohang.getSelectedRow();
        try {
            if (slm < Integer.parseInt(tblgiohang.getValueAt(row, 2).toString())) {
                for (int i = 0; i < listhdct.size(); i++) {
                    int thanhtien = 0;
                    if (listhdct.get(i).getMaSP().equals(tblgiohang.getValueAt(row, 0))) {
                        listhdct.get(i).setMaSP(tblgiohang.getValueAt(row, 0).toString());
                        listhdct.get(i).setTenSP(tblgiohang.getValueAt(row, 1).toString());
                        listhdct.get(i).setDonGia((BigDecimal) tblgiohang.getValueAt(row, 3));
                        listhdct.get(i).setSoLuong(Integer.parseInt(tblgiohang.getValueAt(row, 2).toString()) - slm);
                        thanhtien = thanhtien + (listhdct.get(i).getSoLuong() * Integer.parseInt(listhdct.get(i).getDonGia().toString()));
                        txtThanhTien1.setText((String.valueOf(thanhtien)));
                        hd.setSoLuong(listhdct.get(i).getSoLuong());
                        ChiTietSP CT = new ChiTietSP();
                        CT.setSoLuong(Integer.parseInt(tbldssanpham.getValueAt(row, 3).toString()));
                        CT.setSoLuong(CT.getSoLuong() + slm);
                        chiTietSPService.updatesl(CT, tbldssanpham.getValueAt(row, 0).toString());
                        loadTableChiTietSPBH();
                        addTableGioHang(listhdct);
                        HDCT.updateSL(tblgiohang.getValueAt(row, 0).toString(), hd);
                    }
                }
            } else if (slm == Integer.parseInt(tblgiohang.getValueAt(row, 2).toString())) {
                for (int i = 0; i < listhdct.size(); i++) {
                    if (listhdct.get(i).getMaSP().equals(tblgiohang.getValueAt(row, 0))) {
                        listhdct.remove(i);
                    }
                }
                HDCT.deleteSL(tblgiohang.getValueAt(row, 0).toString());
                ChiTietSP CT = new ChiTietSP();
                CT.setSoLuong(Integer.parseInt(tbldssanpham.getValueAt(row, 3).toString()));
                CT.setSoLuong(CT.getSoLuong() + slm);
                chiTietSPService.updatesl(CT, tbldssanpham.getValueAt(row, 0).toString());
                loadTableChiTietSPBH();
                addTableGioHang(listhdct);
            } else if (slm > Integer.parseInt(tblgiohang.getValueAt(row, 2).toString())) {
                JOptionPane.showMessageDialog(this, "Số lượng nhập lớn hơn trong giỏ hàng");
            } else {
                return;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void tbldssanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldssanphamMouseClicked

    }//GEN-LAST:event_tbldssanphamMouseClicked

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        if (txtMaHdBH.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mời chọn hóa đơn");
        } else {
            int row = tbldssanpham.getSelectedRow();
            int ro = tblgiohang.getSelectedRow();
            int r = tbHoaDonBanHang.getSelectedRow();
            HoaDonChiTietViewModel chiTietHoaDonViewModel = new HoaDonChiTietViewModel();
            List<ChiTietSPViewModel> lctsp1 = chiTietSPService.all();
            ChiTietSPViewModel ctsp = lctsp1.get(row);
            UUID id = ctsp.getIdCTSP();
            ChiTietSP CT = new ChiTietSP();
            String sl = JOptionPane.showInputDialog("Mời nhập số lượng");
            int slm = Integer.valueOf(sl);
            CT.setSoLuong(Integer.parseInt(tbldssanpham.getValueAt(row, 3).toString()));
            CT.setSoLuong(CT.getSoLuong() - slm);
            chiTietHoaDonViewModel.setMaSP((String) tbldssanpham.getValueAt(row, 0));
            chiTietHoaDonViewModel.setTenSP((String) tbldssanpham.getValueAt(row, 1));
            chiTietHoaDonViewModel.setSoLuong(Integer.valueOf(sl));
            chiTietHoaDonViewModel.setDonGia((BigDecimal) tbldssanpham.getValueAt(row, 2));
            HoaDonChiTiet hd = new HoaDonChiTiet();
            hd.setSoLuong(Integer.valueOf(sl));
            hd.setDonGia((BigDecimal) tbldssanpham.getValueAt(row, 2));
            listhdct.add(chiTietHoaDonViewModel);
            listhdctt.add(hd);

            try {
                chiTietSPService.updatesl(CT, tbldssanpham.getValueAt(row, 0).toString());
                addTableGioHang(listhdct);
                loadTableChiTietSPBH();
                HDCT.add(tbldssanpham.getValueAt(row, 0).toString(), tbHoaDonBanHang.getValueAt(r, 0).toString(), hd);
                int thanhtien = 0;
                int slsp = 0;
                if (tblgiohang.getRowCount() > 0) {
                    for (int i = 0; i < listhdct.size(); i++) {
                        thanhtien = thanhtien + (listhdct.get(i).getSoLuong() * Integer.parseInt(listhdct.get(i).getDonGia().toString()));
                    }
                    txtThanhTien1.setText((String.valueOf(thanhtien)));
                }
                if (tblgiohang.getRowCount() > 0) {
                    for (int i = 0; i < listhdct.size(); i++) {
                        slsp = slsp + (listhdct.get(i).getSoLuong());
                    }
                    chiTietHoaDonViewModel.setSoLuong(slsp);
                    //                HDCT.updateSL(hd,id);
                }

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed
        String search = txttimkiem.getText();
        listCTSPVM = chiTietSPService.search(search);
        searchSPBH(listCTSPVM);
    }//GEN-LAST:event_btntimkiemActionPerformed

    private void tbHoaDonBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHoaDonBanHangMouseClicked
        // TODO add your handling code here:
        int row = tbHoaDonBanHang.getSelectedRow();
        txtMaHdBH.setText(tbHoaDonBanHang.getValueAt(row, 0).toString());
        LBtime.setText(tbHoaDonBanHang.getValueAt(row, 1).toString());
    }//GEN-LAST:event_tbHoaDonBanHangMouseClicked

    private void txttenkh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttenkh1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttenkh1ActionPerformed

    private void btnxacnhan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxacnhan1ActionPerformed
        // TODO add your handling code here:
//        CardLayout layout = (CardLayout) pnlCacGiaoDien.getLayout();
//        layout.show(pnlCacGiaoDien, "cardLayThongTin");
//        listKH = serviceKH.getAll();
//        showDataKH(listKH);
        //        KH1 kh = new KH1();
        //        kh.setVisible(true);
    }//GEN-LAST:event_btnxacnhan1ActionPerformed

    private void btnthanhtoan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthanhtoan2ActionPerformed
        // TODO add your handling code here:
        Date date = new Date(System.currentTimeMillis());
        HoaDon hd = new HoaDon();
        int row = tbHoaDonBanHang.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn trong dòng");
            return;
        }
        String ma = cbTenKH.getSelectedItem().toString();
        String ma1 = cbMaNhanVien.getSelectedItem().toString();

        hd.setMaHD(txtMaHdBH.getText());
        hd.setNgayThanhToan(new Date());

        if (rdTienMat.isSelected()) {
            hd.setPTGD(0);
        } else {
            hd.setPTGD(1);
        }
        hd.setTinhTrang(1);
        hd.setTongTien(BigDecimal.valueOf(Double.parseDouble(txtThanhTien1.getText())));
        try {
            hoaDonBanHangService.update(hd, ma, ma1);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        listhdct.clear();
//        loadTableHoaDon();
        loadTableHoaDonBanHang();
        addTableGioHang(listhdct);

    }//GEN-LAST:event_btnthanhtoan2ActionPerformed

    private void txtKhachTra1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtKhachTra1CaretUpdate
        // TODO add your handling code here:
        if (txtKhachTra1.getText().equalsIgnoreCase("")) {
            return;
        } else {
            double tiendu = Double.parseDouble(txtKhachTra1.getText()) - Double.parseDouble(txtThanhTien1.getText());
            txtTienDu1.setText(String.valueOf(tiendu));
        }
    }//GEN-LAST:event_txtKhachTra1CaretUpdate

    private void LBtimeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_LBtimeAncestorAdded
        // TODO add your handling code here:
        //        Time times = new Time(LBtime);
        //        times.start();
    }//GEN-LAST:event_LBtimeAncestorAdded

    private void btnhuyhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhuyhdActionPerformed
        if (txtMaHdBH.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Xin mời chọn hóa đơn cần xóa");
            return;
        } else {
            int bb = JOptionPane.showConfirmDialog(this, "Xoá hóa đơn", "Thông báo", JOptionPane.YES_OPTION, JOptionPane.NO_OPTION);
            if (bb == JOptionPane.YES_OPTION) {
                String Ma = txtMaHdBH.getText();
                try {
                    hoaDonBanHangService.delete(Ma);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
                JOptionPane.showMessageDialog(this, "Xoá thành công");
            } else if (bb == JOptionPane.NO_OPTION) {
                return;
            } else {
                return;
            }
        }
        loadTableHoaDonBanHang();
        addTableGioHang(listhdct);
    }//GEN-LAST:event_btnhuyhdActionPerformed

    private void btntaohd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntaohd1ActionPerformed
        // TODO add your handling code here:
        int bb = JOptionPane.showConfirmDialog(this, "Thêm hóa đơn", "Thông báo", JOptionPane.YES_OPTION, JOptionPane.NO_OPTION);
        if (bb == JOptionPane.YES_OPTION) {
            Date date = new Date(System.currentTimeMillis());
            HoaDon hd = new HoaDon();
            List<HoaDonBanHangViewModel> st = hoaDonBanHangService.all();
            for (int i = 0; i < 5 + 1; i++) {
                Random rdm = new Random();
                int rdmm = rdm.nextInt(100) + 1;
                hd.setMaHD("HD" + rdmm);
            }
            hd.setNgayTao(new Date());
            hd.setTinhTrang(0);
            try {
                hoaDonBanHangService.add(hd);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            loadTableHoaDonBanHang();
            JOptionPane.showMessageDialog(this, "Thêm hóa đơn thành công");
        } else if (bb == JOptionPane.NO_OPTION) {
            return;
        } else {
            return;
        }

    }//GEN-LAST:event_btntaohd1ActionPerformed

    private void txtThanhTien1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtThanhTien1CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThanhTien1CaretUpdate

    private void txtSDTKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTKhachHangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBtime;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnhuyhd;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btntaohd1;
    private javax.swing.JButton btnthanhtoan2;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton btnxacnhan1;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbMaNhanVien;
    private javax.swing.JComboBox<String> cbTenKH;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel pnlBanHang;
    private javax.swing.JRadioButton rdChuyenKhoan;
    private javax.swing.JRadioButton rdTienMat;
    private javax.swing.JTable tbHoaDonBanHang;
    private javax.swing.JTable tbldssanpham;
    private javax.swing.JTable tblgiohang;
    private javax.swing.JTextField txtGhiChu1;
    private javax.swing.JTextField txtKhachTra1;
    private javax.swing.JTextField txtMaHdBH;
    private javax.swing.JTextField txtSDTKhachHang;
    private javax.swing.JTextField txtThanhTien1;
    private javax.swing.JLabel txtTienDu1;
    private javax.swing.JTextField txttenkh1;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
